import type { User } from "@/features/users/types/user.types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ana Beatriz Souza",
    gender: "female",
    age: 24,
    email: "ana.souza@example.com",
  },
  {
    id: "2",
    name: "Carlos Eduardo Lima",
    gender: "male",
    age: 31,
    email: "carlos.lima@example.com",
  },
  {
    id: "3",
    name: "Fernanda Costa",
    gender: "female",
    age: 45,
    email: "fernanda.costa@example.com",
  },
  {
    id: "4",
    name: "Ricardo Nogueira",
    gender: "male",
    age: 19,
    email: "ricardo.nogueira@example.com",
  },
  {
    id: "5",
    name: "Juliana Alves",
    gender: "female",
    age: 52,
    email: "juliana.alves@example.com",
  },
  {
    id: "6",
    name: "Pedro Henrique Martins",
    gender: "male",
    age: 27,
    email: "pedro.martins@example.com",
  },
  {
    id: "7",
    name: "Camila Rocha",
    gender: "female",
    age: 38,
    email: "camila.rocha@example.com",
  },
  {
    id: "8",
    name: "Bruno Ferreira",
    gender: "male",
    age: 60,
    email: "bruno.ferreira@example.com",
  },
  {
    id: "9",
    name: "Larissa Mendes",
    gender: "female",
    age: 22,
    email: "larissa.mendes@example.com",
  },
  {
    id: "10",
    name: "Gabriel Santos",
    gender: "male",
    age: 34,
    email: "gabriel.santos@example.com",
  },
  {
    id: "11",
    name: "Alex Rivera",
    gender: "other",
    age: 29,
    email: "alex.rivera@example.com",
  },
  {
    id: "12",
    name: "Mariana Pires",
    gender: "female",
    age: 41,
    email: "mariana.pires@example.com",
  },
  {
    id: "13",
    name: "Thiago Barbosa",
    gender: "male",
    age: 18,
    email: "thiago.barbosa@example.com",
  },
  {
    id: "14",
    name: "Sofia Ramos",
    gender: "female",
    age: 65,
    email: "sofia.ramos@example.com",
  },
  {
    id: "15",
    name: "Jordan Blake",
    gender: "other",
    age: 33,
    email: "jordan.blake@example.com",
  },
  {
    id: "16",
    name: "Renata Duarte",
    gender: "female",
    age: 28,
    email: "renata.duarte@example.com",
  },
  {
    id: "17",
    name: "Felipe Cardoso",
    gender: "male",
    age: 47,
    email: "felipe.cardoso@example.com",
  },
  {
    id: "18",
    name: "Beatriz Nunes",
    gender: "female",
    age: 20,
    email: "beatriz.nunes@example.com",
  },
  {
    id: "19",
    name: "Diego Teixeira",
    gender: "male",
    age: 55,
    email: "diego.teixeira@example.com",
  },
  {
    id: "20",
    name: "Casey Morgan",
    gender: "other",
    age: 26,
    email: "casey.morgan@example.com",
  },
];
